In [12]:
import pandas as pd
import numpy as np

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [13]:
master = pd.read_csv(
    'cleaned_master_dataset.csv'
)

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [14]:
master.shape

(82365, 39)

# Check available product columns

In [15]:
[
    c for c in master.columns
    if 'product' in c.lower()
]

['product_id',
 'product_category_name',
 'product_name_lenght',
 'product_description_lenght',
 'product_photos_qty',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm',
 'product_category_name_english']

# Top Revenue Categories

In [16]:
category_revenue = (
    master
    .groupby(
        'product_category_name_english'
    )['revenue']
    .sum()
    .reset_index()
    .sort_values(
        'revenue',
        ascending=False
    )
)

category_revenue.head(10)

   product_category_name_english    revenue
71                 watches_gifts  743296.92
44                 health_beauty  737409.81
8                 bed_bath_table  625785.69
66                sports_leisure  590918.46
16         computers_accessories  540672.77
40               furniture_decor  440672.31
50                    housewares  392340.16
21                    cool_stuff  381264.17
6                           auto  360329.79
43                  garden_tools  292393.44

# Most Sold Categories

In [17]:
top_categories = (
    master
    .groupby(
        'product_category_name_english'
    )
    .size()
    .reset_index(
        name='Total_Sales'
    )
    .sort_values(
        'Total_Sales',
        ascending=False
    )
)

top_categories.head(10)

   product_category_name_english  Total_Sales
0                        Unknown        15343
8                 bed_bath_table         6725
44                 health_beauty         5749
66                sports_leisure         5156
40               furniture_decor         5029
16         computers_accessories         4653
50                    housewares         4282
71                 watches_gifts         3649
69                     telephony         2750
43                  garden_tools         2712

# Top Revenue Products

In [18]:
master[
[
'product_id',
'revenue'
]
].sort_values(
    'revenue',
    ascending=False
).head(10)

                             product_id  revenue
25750  489ae2aa008f021502940f251d4cce7f  6735.00
62071  a6492cc69376c469ab6f61d8f44de961  4799.00
47010  c3ed642d592594bb648ff4a04cee2747  4690.00
47026  259037a6a41845e455183f89c5035f18  4590.00
13503  a1beef8f3992dbd4cd8726796aa69c53  4399.87
22597  6cdf8fc1d741c76586d8b6b15e9eef30  4099.99
3102   dd113cb02b2af9c8e5787e8f1f0722f6  4059.00
66353  6902c1962dd19d540807d0ab8fade5c6  3999.90
8825   4ca7b91a31637bd24fb8e559d5e015e4  3999.00
8824   4ca7b91a31637bd24fb8e559d5e015e4  3999.00

# Product KPIs

In [19]:
print(
    "Average Revenue:",
    round(master['revenue'].mean(),2)
)

print(
    "Maximum Revenue:",
    round(master['revenue'].max(),2)
)

print(
    "Minimum Revenue:",
    round(master['revenue'].min(),2)
)

Average Revenue: 99.8
Maximum Revenue: 6735.0
Minimum Revenue: 0.0

In [21]:
monthly_revenue = (
    master
    .groupby(
        [
            'purchase_year',
            'purchase_month'
        ]
    )['revenue']
    .sum()
    .reset_index()
)

monthly_revenue.head()

   purchase_year  purchase_month    revenue
0           2016               9     207.86
1           2016              10   28266.76
2           2016              12      10.90
3           2017               1   75760.07
4           2017               2  140525.16

In [22]:
category_revenue.to_csv(
    'product_category_revenue.csv',
    index=False
)

monthly_revenue.to_csv(
    'monthly_revenue.csv',
    index=False
)

top_categories.to_csv(
    'top_categories.csv',
    index=False
)

print("Files Saved Successfully")

Files Saved Successfully

In [23]:
import os

os.listdir()

['.config',
 'cleaned_master_dataset.csv',
 'monthly_revenue.csv',
 '.ipynb_checkpoints',
 'top_categories.csv',
 'product_category_revenue.csv',
 'sample_data']

# Top 10 Categories by Average Revenue

In [24]:
avg_category_revenue = (
    master
    .groupby('product_category_name_english')['revenue']
    .mean()
    .sort_values(ascending=False)
)

avg_category_revenue.head(10)

product_category_name_english
computers                                1089.734651
small_appliances_home_oven_and_coffee     517.615238
home_appliances_2                         435.719467
agro_industry_and_commerce                325.751731
musical_instruments                       316.821050
small_appliances                          296.597160
fixed_telephony                           268.397564
construction_tools_safety                 223.235750
music                                     204.232609
watches_gifts                             203.698800
Name: revenue, dtype: float64

# Product Category Count

In [26]:
master[
    'product_category_name_english'
].nunique()

72

# Revenue Contribution %

In [28]:
top5 = (
    category_revenue.head(5)
)

top5['Contribution_%'] = (
    top5['revenue']
    /
    category_revenue['revenue'].sum()
    * 100
)

top5

/tmp/ipykernel_3483/1529129116.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top5['Contribution_%'] = (

   product_category_name_english    revenue  Contribution_%
71                 watches_gifts  743296.92        9.042823
44                 health_beauty  737409.81        8.971201
8                 bed_bath_table  625785.69        7.613201
66                sports_leisure  590918.46        7.189013
16         computers_accessories  540672.77        6.577732

In [30]:
avg_category_revenue.to_csv(
    'avg_category_revenue.csv'
)