In [1]:
import pandas as pd
import numpy as np

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [2]:
customer_360 = pd.read_csv(
    'customer_360.csv'
)

product_category = pd.read_csv(
    'product_category_revenue.csv'
)

customer_churn = pd.read_csv(
    'customer_churn.csv'
)

print(
    "Datasets Loaded Successfully"
)

Datasets Loaded Successfully

# Campaign Recommendation Engine

In [3]:
def campaign_type(persona):

    if persona == 'Elite VIP':
        return 'Premium Rewards Campaign'

    elif persona == 'VIP Customer':
        return 'Loyalty Programme Campaign'

    elif persona == 'Loyal Customer':
        return 'Customer Appreciation Campaign'

    elif persona == 'At Risk Customer':
        return 'Retention Campaign'

    elif persona == 'Inactive Customer':
        return 'Win Back Campaign'

    else:
        return 'Standard Promotion'


customer_360[
    'Recommended_Campaign'
] = customer_360[
    'Customer_Persona'
].apply(
    campaign_type
)

customer_360[
    [
        'Customer_Persona',
        'Recommended_Campaign'
    ]
].head()

    Customer_Persona        Recommended_Campaign
0  Inactive Customer           Win Back Campaign
1   At Risk Customer          Retention Campaign
2  Inactive Customer           Win Back Campaign
3       VIP Customer  Loyalty Programme Campaign
4  Inactive Customer           Win Back Campaign

# Customer Targeting Engine

In [4]:
target_customers = (
    customer_360
    .sort_values(
        'Strategic_Value_Score',
        ascending=False
    )
)

target_customers[
    [
        'customer_unique_id',
        'Customer_Persona',
        'Strategic_Value_Score'
    ]
].head(20)

,customer_unique_id,Customer_Persona,Strategic_Value_Score
53906,c7794313e2cd53472b116a751350f132,VIP Customer,68.38
64274,edde2314c6c30e864a128ac95d6b2112,VIP Customer,67.69
54667,ca27f3dac28fb1063faddd424c9d95fa,VIP Customer,66.36
632,025cf7c2f32536f0be1ab412bb6602d2,VIP Customer,65.32
55747,ce3fe361f9e68bf0a813baaae1334d01,VIP Customer,63.83
39081,910f0afb84bc778e856d3683c7e8a46a,VIP Customer,63.69
67120,f886a3f43af9ac928fbb4b56436c528c,VIP Customer,63.50
54141,c8460e4251689ba205045f3ea17884a1,VIP Customer,62.88
18955,46450c74a0d8c5ca9395da1daac6c120,VIP Customer,62.31
38218,8e07cbdbbb24328ece74135e2a81405b,VIP Customer,61.20
42557,9db254a87951220e74c58549749cf128,VIP Customer,61.08
37329,8a8ac60fd8ea25925f379a33ef277987,VIP Customer,61.08
35925,85475e754525d6d222d917dbc8251801,VIP Customer,60.92
10901,287a7cdacbcda8f842d7719e77cb8457,VIP Customer,60.47
212,00c07da5ba0e07b4f248a3a373b07476,VIP Customer,60.38
4611,10e1df2717597281c5cffa0e0a7ca7cb,VIP Customer,60.23
62639,e79c794eb044c594d923722240125052,VIP Customer,60.19
60730,e0a7e61d37dd4060ab419bdb93a9f05d,VIP Customer,60.13
24318,5a04d5472eb5ee998250f0977b31f772,VIP Customer,60.12
62761,e8258022c5060b1f3d861556a17fd741,VIP Customer,59.93

# Revenue Leakage Detector

In [5]:
lowest_categories = (
    product_category
    .sort_values(
        'revenue'
    )
    .head(5)
)

lowest_categories

   product_category_name_english  revenue
71         security_and_services   283.29
70     fashion_childrens_clothes   419.86
69             cds_dvds_musicals   465.00
68                home_comfort_2   618.37
67                       flowers   673.55

In [6]:
print(
    "AI Insight:"
)

print(
    "These categories require pricing, marketing or inventory review."
)

AI Insight:
These categories require pricing, marketing or inventory review.

# Revenue Opportunity Finder

In [7]:
top_categories = (
    product_category
    .sort_values(
        'revenue',
        ascending=False
    )
    .head(5)
)

top_categories

  product_category_name_english    revenue
0                 watches_gifts  743296.92
1                 health_beauty  737409.81
2                bed_bath_table  625785.69
3                sports_leisure  590918.46
4         computers_accessories  540672.77

In [8]:
print(
    "AI Insight:"
)

print(
    "These categories represent the strongest growth opportunities."
)

AI Insight:
These categories represent the strongest growth opportunities.

# Upsell Intelligence Engine

In [9]:
upsell_customers = (
    customer_360[
        customer_360[
            'Customer_Persona'
        ].isin(
            [
                'VIP Customer',
                'Elite VIP'
            ]
        )
    ]
)

upsell_customers[
    [
        'customer_unique_id',
        'Customer_Persona'
    ]
].head(20)

                  customer_unique_id Customer_Persona
3   00053a61a98854899e70ed204dd4bafe     VIP Customer
15  0010a452c6d13139e50b57f19f52e04e     VIP Customer
17  001147e649a7b1afd577e873841632dd     VIP Customer
20  0011857aff0e5871ce5eb429f21cdaf5     VIP Customer
29  0019e8c501c85848ac0966d45226fa1d     VIP Customer
31  001a34eb30ecb8e3aacb07c475ca4dd1     VIP Customer
34  002043098f10ba39a4600b6c52fbfe3c     VIP Customer
39  0028a7d8db7b0247652509358ad8d755     VIP Customer
41  00293787e2aec37a9c253b63fdfe2049     VIP Customer
47  002cdf87d4c03f08f7eb4551a923affc     VIP Customer
54  003162bf0351f47a1a247992b8b9b42d     VIP Customer
58  0033f4a2887e07e25aa1204d482f41ba     VIP Customer
59  00344274804f3b8003de1b0562ae01df     VIP Customer
62  0036b4a3d09ad551a5188c2e374da402     VIP Customer
65  0037aa56b017c105c3a9d47af71fff98     VIP Customer
70  003a5571a07dcf09bf117d13d2980ba3     VIP Customer
73  003ae409f37c3c30cb1c974af3a42692     VIP Customer
75  003d56767e53e08671de00da3fba8d40     VIP Customer
77  003f4901fdb60ae9c1e2538b84c208e1     VIP Customer
80  004177f7bf62929186b32c7fdaa6157b     VIP Customer

# Retention Campaign Generator

In [10]:
retention_customers = (
    customer_360[
        customer_360[
            'Retention_Priority_Score'
        ] > 70
    ]
)

retention_customers[
    [
        'customer_unique_id',
        'Retention_Priority_Score'
    ]
].head(20)

                  customer_unique_id  Retention_Priority_Score
1   0000f46a3911fa3c0805444483337064                     90.22
2   0004aac84e0df4da2b147fca70cf8255                     77.44
3   00053a61a98854899e70ed204dd4bafe                     71.44
4   0005ef4cd20d2893f0d9fbd94d3c0d97                     71.23
5   0006fdc98a402fceb4eb0ee528f6a8d4                     83.63
6   00082cbe03e478190aadbea78542e933                     77.11
7   00090324bbad0e9342388303bb71ba0a                     70.69
9   000a5ad9c4601d2bbdd9ed765d5213b3                     82.41
10  000bfa1d2f1a41876493be685390d6d3                     79.87
11  000d460961d6dbfa3ec6c9f5805769e1                     74.60
15  0010a452c6d13139e50b57f19f52e04e                     83.57
16  0010fb34b966d44409382af9e8fd5b77                     71.67
17  001147e649a7b1afd577e873841632dd                     81.12
18  00115fc7123b5310cf6d3a3aa932699e                     92.72
19  0011805441c0d1b68b48002f1d005526                     88.05
20  0011857aff0e5871ce5eb429f21cdaf5                     84.42
21  0014a5a58da615f7b01a4f5e194bf5ea                     73.95
24  00191a9719ef48ebb5860b130347bf33                     88.23
25  001926cef41060fae572e2e7b30bd2a4                     82.02
28  00196fdb2bf9edfc35e88ebfbcf8d781                     72.24

In [15]:
retention_customers[
    'Retention_Campaign'
] = (
    'Special Discount Offer'
)

In [16]:
retention_customers = (
    retention_customers.copy()
)

retention_customers.loc[
    :,
    'Retention_Campaign'
] = 'Special Discount Offer'

# Marketing ROI Priority Matrix

In [17]:
customer_360[
    'Marketing_Priority'
] = np.where(

    customer_360[
        'Strategic_Value_Score'
    ] > 80,

    'High',

    'Normal'

)

customer_360[
    'Marketing_Priority'
].value_counts()

Marketing_Priority
Normal    69127
Name: count, dtype: int64

# AI Marketing Advisor

In [18]:
print(
    "AI MARKETING ADVISOR"
)

print(
    "------------------------"
)

print(
    "Focus marketing spend on high-value customers."
)

print(
    "Run retention campaigns for at-risk customers."
)

print(
    "Expand top-performing categories."
)

print(
    "Upsell Elite VIP customers."
)

print(
    "Review low-performing categories."
)

AI MARKETING ADVISOR
------------------------
Focus marketing spend on high-value customers.
Run retention campaigns for at-risk customers.
Expand top-performing categories.
Upsell Elite VIP customers.
Review low-performing categories.

# Executive Marketing Report

In [19]:
marketing_report = f"""

EXECUTIVE MARKETING REPORT

Top Revenue Categories:
{list(top_categories.iloc[:,0].head(3))}

Lowest Revenue Categories:
{list(lowest_categories.iloc[:,0].head(3))}

Marketing Focus Areas:

1. Retention Campaigns

2. Upsell VIP Customers

3. Expand High Revenue Categories

4. Improve Low Revenue Categories

"""

print(
    marketing_report
)

EXECUTIVE MARKETING REPORT

Top Revenue Categories:
['watches_gifts', 'health_beauty', 'bed_bath_table']

Lowest Revenue Categories:
['security_and_services', 'fashion_childrens_clothes', 'cds_dvds_musicals']

Marketing Focus Areas:

1. Retention Campaigns

2. Upsell VIP Customers

3. Expand High Revenue Categories

4. Improve Low Revenue Categories

In [20]:
customer_360.to_csv(
    'marketing_intelligence_customers.csv',
    index=False
)

retention_customers.to_csv(
    'retention_campaign_customers.csv',
    index=False
)

top_categories.to_csv(
    'marketing_opportunities.csv',
    index=False
)

print(
    "Marketing Intelligence Datasets Exported Successfully"
)

Marketing Intelligence Datasets Exported Successfully

# Marketing Health Index

In [22]:
marketing_health = 100

if len(retention_customers) > 10000:
    marketing_health -= 20

if len(lowest_categories) > 3:
    marketing_health -= 20

print(
    "Marketing Health Index:",
    marketing_health,
    "/100"
)

Marketing Health Index: 60 /100

# Customer Conversion Score

In [23]:
customer_360[
    'Conversion_Score'
] = (

    customer_360[
        'Customer_Health_Index'
    ] * 0.5

    +

    customer_360[
        'Strategic_Value_Score'
    ] * 0.5

)

customer_360[
    [
        'customer_unique_id',
        'Conversion_Score'
    ]
].head()

                 customer_unique_id  Conversion_Score
0  0000366f3b9a7992bf8c76cfdf3221e2            26.920
1  0000f46a3911fa3c0805444483337064             8.390
2  0004aac84e0df4da2b147fca70cf8255            19.175
3  00053a61a98854899e70ed204dd4bafe            24.700
4  0005ef4cd20d2893f0d9fbd94d3c0d97            24.575

# Campaign Priority Ranking

In [24]:
campaign_priority = (
    customer_360
    .sort_values(
        'Conversion_Score',
        ascending=False
    )
)

campaign_priority.head(20)

,customer_unique_id,CLTV,Customer_Health_Index,Dynamic_Risk_Score,Customer_Persona,Next_Best_Action,Customer_Influence_Score,Strategic_Value_Score,Retention_Priority_Score,Lifecycle_Stage,Recommended_Campaign,Marketing_Priority,Conversion_Score
53906,c7794313e2cd53472b116a751350f132,4598.00,83.03,16.97,VIP Customer,VIP Loyalty Benefits,58.62,68.38,16.97,Loyal Stage,Loyalty Programme Campaign,Normal,75.705
64274,edde2314c6c30e864a128ac95d6b2112,4399.87,82.67,17.33,VIP Customer,VIP Loyalty Benefits,57.70,67.69,17.33,Loyal Stage,Loyalty Programme Campaign,Normal,75.180
54667,ca27f3dac28fb1063faddd424c9d95fa,4059.00,81.85,18.15,VIP Customer,VIP Loyalty Benefits,56.03,66.36,18.15,Loyal Stage,Loyalty Programme Campaign,Normal,74.105
632,025cf7c2f32536f0be1ab412bb6602d2,3576.00,81.91,18.09,VIP Customer,VIP Loyalty Benefits,54.26,65.32,18.09,Loyal Stage,Loyalty Programme Campaign,Normal,73.615
55747,ce3fe361f9e68bf0a813baaae1334d01,3099.00,81.30,18.70,VIP Customer,VIP Loyalty Benefits,52.18,63.83,18.70,Loyal Stage,Loyalty Programme Campaign,Normal,72.565
67120,f886a3f43af9ac928fbb4b56436c528c,2999.90,81.15,18.85,VIP Customer,VIP Loyalty Benefits,51.74,63.50,18.85,Loyal Stage,Loyalty Programme Campaign,Normal,72.325
39081,910f0afb84bc778e856d3683c7e8a46a,3300.00,80.47,19.53,VIP Customer,VIP Loyalty Benefits,52.51,63.69,19.53,Loyal Stage,Loyalty Programme Campaign,Normal,72.080
54141,c8460e4251689ba205045f3ea17884a1,3060.00,80.08,19.92,VIP Customer,VIP Loyalty Benefits,51.42,62.88,19.92,Loyal Stage,Loyalty Programme Campaign,Normal,71.480
42557,9db254a87951220e74c58549749cf128,2160.00,80.37,19.63,VIP Customer,VIP Loyalty Benefits,48.22,61.08,19.63,Loyal Stage,Loyalty Programme Campaign,Normal,70.725
18955,46450c74a0d8c5ca9395da1daac6c120,3109.99,79.10,20.90,VIP Customer,VIP Loyalty Benefits,51.12,62.31,20.90,Loyal Stage,Loyalty Programme Campaign,Normal,70.705
37329,8a8ac60fd8ea25925f379a33ef277987,2258.00,80.05,19.95,VIP Customer,VIP Loyalty Benefits,48.43,61.08,19.95,Loyal Stage,Loyalty Programme Campaign,Normal,70.565
38218,8e07cbdbbb24328ece74135e2a81405b,2350.00,79.93,20.07,VIP Customer,VIP Loyalty Benefits,48.71,61.20,20.07,Loyal Stage,Loyalty Programme Campaign,Normal,70.565
35925,85475e754525d6d222d917dbc8251801,2399.00,79.38,20.62,VIP Customer,VIP Loyalty Benefits,48.61,60.92,20.62,Loyal Stage,Loyalty Programme Campaign,Normal,70.150
10901,287a7cdacbcda8f842d7719e77cb8457,2150.00,79.53,20.47,VIP Customer,VIP Loyalty Benefits,47.76,60.47,20.47,Loyal Stage,Loyalty Programme Campaign,Normal,70.000
4611,10e1df2717597281c5cffa0e0a7ca7cb,1999.98,79.66,20.34,VIP Customer,VIP Loyalty Benefits,47.27,60.23,20.34,Loyal Stage,Loyalty Programme Campaign,Normal,69.945
24318,5a04d5472eb5ee998250f0977b31f772,1999.90,79.51,20.49,VIP Customer,VIP Loyalty Benefits,47.20,60.12,20.49,Loyal Stage,Loyalty Programme Campaign,Normal,69.815
212,00c07da5ba0e07b4f248a3a373b07476,2258.00,79.06,20.94,VIP Customer,VIP Loyalty Benefits,47.93,60.38,20.94,Loyal Stage,Loyalty Programme Campaign,Normal,69.720
60730,e0a7e61d37dd4060ab419bdb93a9f05d,2090.00,79.23,20.77,VIP Customer,VIP Loyalty Benefits,47.39,60.13,20.77,Loyal Stage,Loyalty Programme Campaign,Normal,69.680
62639,e79c794eb044c594d923722240125052,2199.00,78.98,21.02,VIP Customer,VIP Loyalty Benefits,47.67,60.19,21.02,Loyal Stage,Loyalty Programme Campaign,Normal,69.585
62761,e8258022c5060b1f3d861556a17fd741,2029.00,79.15,20.85,VIP Customer,VIP Loyalty Benefits,47.12,59.93,20.85,Loyal Stage,Loyalty Programme Campaign,Normal,69.540

# Customer Acquisition Intelligence

In [25]:
potential_targets = (
    customer_360[
        customer_360[
            'Conversion_Score'
        ] > 75
    ]
)

print(
    "High Potential Marketing Targets:"
)

print(
    len(potential_targets)
)

High Potential Marketing Targets:
2

# Marketing Opportunity Score

In [26]:
opportunity_score = (

    top_categories[
        'revenue'
    ].sum()

    /

    product_category[
        'revenue'
    ].sum()

) * 100

print(
    "Marketing Opportunity Score:",
    round(opportunity_score,2),
    "%"
)

Marketing Opportunity Score: 39.39 %

In [27]:
customer_360.to_csv(
    'marketing_intelligence_customers.csv',
    index=False
)

campaign_priority.to_csv(
    'campaign_priority_customers.csv',
    index=False
)

potential_targets.to_csv(
    'high_potential_customers.csv',
    index=False
)